# Generated by Django 5.0.4 on 2024-04-05 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autor", models.CharField(max_length=255)),
                ("titulo", models.CharField(max_length=255)),
                ("subtitulo", models.CharField(max_length=255)),
                ("conteudo", models.TextField()),
                (
                    "data_publicacao",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 4, 4, 21, 12, 39, 349447)
                    ),
                ),
            ],
        ),
    ]
