# Generated by Django 5.0.4 on 2024-04-05 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="data_publicacao",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 4, 21, 13, 58, 304434)
            ),
        ),
    ]
