# Generated by Django 5.0.4 on 2024-04-05 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_data_publicacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="data_publicacao",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 4, 21, 22, 13, 516867)
            ),
        ),
    ]
