# Generated by Django 5.0.4 on 2024-04-06 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_data_publicacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="data_publicacao",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 6, 17, 11, 2, 304152, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
